In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
torch.__version__

'2.6.0+cpu'

In [3]:
# PyTorch 类似 NumPy 框架
# NumPy 框架本身是一个数值运算(数学运算)的一个框架 --> 内部最核心的 ndarray --> 数组/矩阵
## NumPy常见的操作：创建、乘法、加法、指数、对数、均值、和......

## PyTorch 类似 sklearn 的模型学习的框架，基本操作类似Numpy语法
### 关注PyTorch中的网络的构造(算法结构)、损失函数、优化器

In [4]:
## 重点关注Tensor的创建、模型的创建、损失的创建、优化器的使用

### Tensor创建
Tensor对象是PyTorch中的基本对象，一般用来表示不需要进行参数更新的数据对象

##### 1. 随机创建Tensor对象

In [5]:
## PS: PyTorch中随机创建Tensor默认浮点型为float32，模型整型为int64；默认情况下数据所在设备均在CPU；
## 可以通过dtype给定数据类型、device给定运行设备
x = torch.randn(2, 5)  # 随机创建一个[2,5]的矩阵，满足X~N(0,1)的标准正态分布随机数
# x = torch.randn(2, 5, dtype=torch.float64)  # 随机创建一个[2,5]的矩阵，满足X~N(0,1)的标准正态分布随机数
print(x)
print(f"Shape形状为: {x.shape}")
print(f"数据的类型: {x.dtype}")
print(f"数据所在设备信息: {x.device}")
print(f"是否属于梯度更新参数: {x.requires_grad}")

tensor([[-1.9313,  2.1935,  2.1956, -1.6923, -1.7866],
        [ 0.7493,  0.7125,  0.7545, -0.4476, -0.7763]])
Shape形状为: torch.Size([2, 5])
数据的类型: torch.float32
数据所在设备信息: cpu
是否属于梯度更新参数: False


In [6]:
torch.randint(0, 10, size=(10,)).dtype

torch.int64

In [7]:
print(torch.ones((2,3), dtype=torch.float64))

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
print(torch.zeros((2,3)))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### 2. 基于已有数据创建Tensor对象

In [9]:
## PS: 基于python类型数据可创建tensor对象，一般支持数字或者list数组；
## 创建时候默认会自动推断数据类型，浮点型为float32，整型为int64，设备默认为CPU
## 可以通过dtype给定数据类型、device给定运行设备
## NOTE: Tensor底层和python数据类型不共享内存，相当于是一个副本，更改互不影响
x_py = [1,2,3,4,5,6]
# x_py = 2
x = torch.tensor(x_py)  # python对象转Tensor对象
#x = torch.tensor(x_py, dtype=torch.int32)
xtolst = x.cpu().tolist()  # Tensor对象转换为list --> 仅在cpu设备上的tensor进行转换

print(x)
print(f"Shape形状为: {x.shape}")
print(f"数据的类型: {x.dtype}")
print(f"数据所在设备信息: {x.device}")
print(f"是否属于梯度更新参数: {x.requires_grad}")
if isinstance(x_py, list):
    x_py[0] = 100
    x[1] = 101
    print(f"更改后Python对象为: {x_py}")
    print(f"更改后Tensor对象为: {x}")
print(f"Tensor转换的Python列表对象为: {type(xtolst)} - {xtolst}")


tensor([1, 2, 3, 4, 5, 6])
Shape形状为: torch.Size([6])
数据的类型: torch.int64
数据所在设备信息: cpu
是否属于梯度更新参数: False
更改后Python对象为: [100, 2, 3, 4, 5, 6]
更改后Tensor对象为: tensor([  1, 101,   3,   4,   5,   6])
Tensor转换的Python列表对象为: <class 'list'> - [1, 2, 3, 4, 5, 6]


In [10]:
## PS: 基于Numpy类型数据可创建tensor对象，一般支持数字或者数组；
## 创建时候类型默认和所给定的Numpy类型一致，设备默认为CPU
## torch.tensor：可以通过dtype给定数据类型、device给定运行设备
x_np = np.asarray([1, 2, 3, 4, 5, 6])
x = torch.tensor(x_np)  # Numpy对象转Tensor对象  不共享内存
# x = torch.from_numpy(x_np)  # 直接基于Numpy对象的内存进行Tensor对象创建 -- 共享内存
xtonp = x.numpy()  # Tensor对象转换为Numpy对象（共享内存） --> 仅在cpu设备上的tensor进行转换

print(x)
print(f"Shape形状为: {x.shape}")
print(f"数据的类型: {x.dtype}")
print(f"数据所在设备信息: {x.device}")
print(f"是否属于梯度更新参数: {x.requires_grad}")
x_np[0] = 100
x[1] = 101
print(f"更改后NumPy对象为: {x_np}")
print(f"更改后Tensor对象为: {x}")
print(f"Tensor转换的NumPy列表对象为: {type(xtonp)} - {xtonp}")


tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)
Shape形状为: torch.Size([6])
数据的类型: torch.int32
数据所在设备信息: cpu
是否属于梯度更新参数: False
更改后NumPy对象为: [100   2   3   4   5   6]
更改后Tensor对象为: tensor([  1, 101,   3,   4,   5,   6], dtype=torch.int32)
Tensor转换的NumPy列表对象为: <class 'numpy.ndarray'> - [  1 101   3   4   5   6]


#### Tensor设备、类型、Shape转换

In [11]:
x = torch.randn(3, 6)
print(f"Shape形状为: {x.shape}")
print(f"数据的类型: {x.dtype}")
print(f"数据所在设备信息: {x.device}")
print(f"是否属于梯度更新参数: {x.requires_grad}")
print(x)

Shape形状为: torch.Size([3, 6])
数据的类型: torch.float32
数据所在设备信息: cpu
是否属于梯度更新参数: False
tensor([[ 0.5165,  1.8226, -0.9791, -0.9279,  0.0171,  2.9707],
        [-1.4408,  0.6950, -0.8317,  1.6608,  1.1508, -1.2302],
        [ 1.4483,  3.0294, -1.4802,  0.8377, -0.0916,  1.2640]])


In [12]:
_x = torch.reshape(x, shape=(3, 2, -1))
#_x = x.reshape(shape=(3, 2, -1))
print("torch.reshape后结果为:")
print(f"Shape形状为: {_x.shape}")
print(f"数据的类型: {_x.dtype}")
print(f"数据所在设备信息: {_x.device}")
print(f"是否属于梯度更新参数: {_x.requires_grad}")
print(_x)

torch.reshape后结果为:
Shape形状为: torch.Size([3, 2, 3])
数据的类型: torch.float32
数据所在设备信息: cpu
是否属于梯度更新参数: False
tensor([[[ 0.5165,  1.8226, -0.9791],
         [-0.9279,  0.0171,  2.9707]],

        [[-1.4408,  0.6950, -0.8317],
         [ 1.6608,  1.1508, -1.2302]],

        [[ 1.4483,  3.0294, -1.4802],
         [ 0.8377, -0.0916,  1.2640]]])


In [13]:
# 从效果上来讲，view和reshape都是更改tensor对象的shape形状，但是执行效率和内部逻辑是不一样的，view的效果更高一些，但是view要求tensor对象在内存中必须是连续空间上的值
_x = x.view(2, -1)
# _x = x.T.view(2, -1) # x.T x转置后，数据是不连续的，此时不可以使用view方法
print("Tensor.view后结果为:")
print(f"Shape形状为: {_x.shape}")
print(f"数据的类型: {_x.dtype}")
print(f"数据所在设备信息: {_x.device}")
print(f"是否属于梯度更新参数: {_x.requires_grad}")
print(_x)

Tensor.view后结果为:
Shape形状为: torch.Size([2, 9])
数据的类型: torch.float32
数据所在设备信息: cpu
是否属于梯度更新参数: False
tensor([[ 0.5165,  1.8226, -0.9791, -0.9279,  0.0171,  2.9707, -1.4408,  0.6950,
         -0.8317],
        [ 1.6608,  1.1508, -1.2302,  1.4483,  3.0294, -1.4802,  0.8377, -0.0916,
          1.2640]])


In [14]:
# 使用to命令进行类型或者设备信息的转换
_x = x.to(dtype=torch.float64)
print("to方法转换数据类型后:")
print(f"Shape形状为: {_x.shape}")
print(f"数据的类型: {_x.dtype}")
print(f"数据所在设备信息: {_x.device}")
print(f"是否属于梯度更新参数: {_x.requires_grad}")
print(_x)

to方法转换数据类型后:
Shape形状为: torch.Size([3, 6])
数据的类型: torch.float64
数据所在设备信息: cpu
是否属于梯度更新参数: False
tensor([[ 0.5165,  1.8226, -0.9791, -0.9279,  0.0171,  2.9707],
        [-1.4408,  0.6950, -0.8317,  1.6608,  1.1508, -1.2302],
        [ 1.4483,  3.0294, -1.4802,  0.8377, -0.0916,  1.2640]],
       dtype=torch.float64)


In [15]:
# 当支持GPU的时候，使用cuda，否则使用cpu
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"当前设备为:{device}")
_x = x.to(device=device)
print("to方法转换设备信息后:")
print(f"Shape形状为: {_x.shape}")
print(f"数据的类型: {_x.dtype}")
print(f"数据所在设备信息: {_x.device}")
print(f"是否属于梯度更新参数: {_x.requires_grad}")
print(_x)
print(f"快捷转换到cpu方式:\n{_x.cpu()}")

当前设备为:cpu
to方法转换设备信息后:
Shape形状为: torch.Size([3, 6])
数据的类型: torch.float32
数据所在设备信息: cpu
是否属于梯度更新参数: False
tensor([[ 0.5165,  1.8226, -0.9791, -0.9279,  0.0171,  2.9707],
        [-1.4408,  0.6950, -0.8317,  1.6608,  1.1508, -1.2302],
        [ 1.4483,  3.0294, -1.4802,  0.8377, -0.0916,  1.2640]])
快捷转换到cpu方式:
tensor([[ 0.5165,  1.8226, -0.9791, -0.9279,  0.0171,  2.9707],
        [-1.4408,  0.6950, -0.8317,  1.6608,  1.1508, -1.2302],
        [ 1.4483,  3.0294, -1.4802,  0.8377, -0.0916,  1.2640]])


#### Tensor常见数值运算API
基本操作基本和NumPy里面的数值操作解决，主要区别就是：多tensor之间进行操作的时候，要求必须数据类型、数据所在设备信息均一样；某些封装好的特殊API除外。

In [16]:
# 加法: 所有的数据类型、device信息必须一样
x = torch.randn(2, 3)
# y = 5
# y = torch.rand(3)
y = torch.rand(2, 1)
# y = torch.rand(2, 3)
print(x)
print(y)
print(x + y)

tensor([[-0.8380,  1.3934, -0.2640],
        [ 0.2102, -0.1229, -0.9988]])
tensor([[0.8432],
        [0.7769]])
tensor([[ 0.0052,  2.2366,  0.5792],
        [ 0.9871,  0.6540, -0.2219]])


In [17]:
# 矩阵的数乘
x = 1.5
y = torch.rand(2, 3)
print(x)
print(y)
print(x * y)

1.5
tensor([[0.2355, 0.6933, 0.6408],
        [0.3429, 0.8878, 0.5640]])
tensor([[0.3533, 1.0400, 0.9612],
        [0.5143, 1.3317, 0.8460]])


In [18]:
# 矩阵的数乘
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)
print(x * y)

tensor([[0.4566, 0.4030, 0.5300],
        [0.0731, 0.1377, 0.1363]])
tensor([[0.0347, 0.3310, 0.9192],
        [0.5337, 0.5201, 0.9545]])
tensor([[0.0158, 0.1334, 0.4872],
        [0.0390, 0.0716, 0.1301]])


In [19]:
# 矩阵的数乘
x = torch.rand(1, 3)
y = torch.rand(2, 3)
print(x)
print(y)
print(x * y)

tensor([[0.3875, 0.4355, 0.7735]])
tensor([[0.2794, 0.9771, 0.4721],
        [0.1300, 0.1764, 0.1204]])
tensor([[0.1083, 0.4255, 0.3652],
        [0.0504, 0.0768, 0.0932]])


In [20]:
# 矩阵乘法
x = torch.rand(2, 3)
y = torch.randn(3, 4)
print(x @ y)
print(torch.matmul(x, y))

tensor([[-0.9537,  0.1798, -0.2073, -0.6113],
        [-0.8958, -0.8409, -0.2412,  0.0581]])
tensor([[-0.9537,  0.1798, -0.2073, -0.6113],
        [-0.8958, -0.8409, -0.2412,  0.0581]])


In [21]:
# 多维矩阵乘法
# 支持广播机制，实际上只有最后两个维度参与矩阵乘法，其它维度相当于遍历
x = torch.randn(2, 3, 2)
y = torch.randn(2, 2, 1)

print(x @ y)
print(torch.matmul(x, y))

for i in range(2):
    print(x[i] @ y[i])

tensor([[[ 1.4984],
         [-0.1138],
         [ 1.6251]],

        [[-0.3817],
         [ 0.3668],
         [-0.8574]]])
tensor([[[ 1.4984],
         [-0.1138],
         [ 1.6251]],

        [[-0.3817],
         [ 0.3668],
         [-0.8574]]])
tensor([[ 1.4984],
        [-0.1138],
        [ 1.6251]])
tensor([[-0.3817],
        [ 0.3668],
        [-0.8574]])


In [22]:
# 求均值
x = torch.randn(2, 3, 5)
print(torch.mean(x, dim=1))  # 按照维度1进行数据均值求解
print(x.mean(dim=1))  # 按照维度1进行数据均值求解
print((x[:, 0, :] + x[:, 1, :] + x[:, 2]) / 3.0)

tensor([[-0.6266, -1.0951, -0.0562,  0.4867,  0.2921],
        [ 0.2255, -0.7678, -0.4444, -1.1154,  0.1407]])
tensor([[-0.6266, -1.0951, -0.0562,  0.4867,  0.2921],
        [ 0.2255, -0.7678, -0.4444, -1.1154,  0.1407]])
tensor([[-0.6266, -1.0951, -0.0562,  0.4867,  0.2921],
        [ 0.2255, -0.7678, -0.4444, -1.1154,  0.1407]])


In [23]:
# 求和
x = torch.randn(2, 3, 5)
print(x.sum(dim=2))  # 按照维度-1也就是维度2 进行数据和求解
print(x[..., 0] + x[..., 1] + x[:, :, 2] + x[:, :, 3] + x[:, :, 4])

tensor([[ 4.2121,  0.1459,  0.0998],
        [-2.6332, -0.7501,  2.4630]])
tensor([[ 4.2121,  0.1459,  0.0998],
        [-2.6332, -0.7501,  2.4630]])


In [24]:
# 绝对值
x = torch.randn(5)
print(x)
print(torch.abs(x))

tensor([-0.9849,  0.2996,  0.6528,  0.3667, -0.0083])
tensor([0.9849, 0.2996, 0.6528, 0.3667, 0.0083])


In [25]:
# 最大数据做大的索引下标
x = torch.randn(2, 5)
print(x)
print(torch.argmax(x, dim=-1)) # 在最后一个维度中选择值最大的对应下标

tensor([[ 0.6267,  1.0219, -0.4958,  0.1472, -0.2713],
        [ 2.0928,  1.1126,  0.3624, -0.0425,  0.9397]])
tensor([1, 0])


In [26]:
# top k：选择前k个比较大的值以及对应的索引id
x = torch.randn(2, 5)
print(x)
print(torch.topk(x, k=3, dim=-1))

tensor([[ 0.5332, -0.1952,  0.2231,  1.2086,  0.5506],
        [ 1.2907,  1.7065,  1.0526, -0.0840, -1.5604]])
torch.return_types.topk(
values=tensor([[1.2086, 0.5506, 0.5332],
        [1.7065, 1.2907, 1.0526]]),
indices=tensor([[3, 4, 0],
        [1, 0, 2]]))


In [27]:
# 数据转置
x = torch.randn(2, 3)
print(x)
print(x.T)
print(torch.transpose(x, dim0=1, dim1=0))

tensor([[-1.4287, -0.6202, -0.7669],
        [ 1.8310, -0.1318,  0.8828]])
tensor([[-1.4287,  1.8310],
        [-0.6202, -0.1318],
        [-0.7669,  0.8828]])
tensor([[-1.4287,  1.8310],
        [-0.6202, -0.1318],
        [-0.7669,  0.8828]])


In [28]:
# 多维数据交换 对应numpy接口为: np.transpose
x = torch.randn(5, 3, 4, 10)
print(x.shape)
print(torch.permute(x, dims=(0, 3, 1, 2)).shape)

torch.Size([5, 3, 4, 10])
torch.Size([5, 10, 3, 4])


In [29]:
# tensor对象分割
x = torch.randn(2,6)
print(x)
# split中split_size_or_sections是给定分割后每个tensor对应维度的大小
print(torch.split(x, split_size_or_sections=3, dim=1))
# chunk中的chunks是预计将对应维度分割成几份
print(torch.chunk(x, chunks=3, dim=1))

tensor([[ 0.8240, -0.5183, -0.5145,  0.8972, -0.0258,  0.8678],
        [ 0.9629, -0.4214,  1.4249, -0.6068, -1.0137,  0.9388]])
(tensor([[ 0.8240, -0.5183, -0.5145],
        [ 0.9629, -0.4214,  1.4249]]), tensor([[ 0.8972, -0.0258,  0.8678],
        [-0.6068, -1.0137,  0.9388]]))
(tensor([[ 0.8240, -0.5183],
        [ 0.9629, -0.4214]]), tensor([[-0.5145,  0.8972],
        [ 1.4249, -0.6068]]), tensor([[-0.0258,  0.8678],
        [-1.0137,  0.9388]]))


In [30]:
# 数据合并
x1 = torch.rand(1,3)
x2 = torch.rand(3,3)
print("=" * 10)
print(x1)
print(x2)
print("=" * 10)
print(torch.cat([x1, x2], dim=0))

tensor([[0.4818, 0.9820, 0.9730]])
tensor([[0.6460, 0.6127, 0.5179],
        [0.9928, 0.3334, 0.0458],
        [0.5579, 0.2503, 0.6177]])
tensor([[0.4818, 0.9820, 0.9730],
        [0.6460, 0.6127, 0.5179],
        [0.9928, 0.3334, 0.0458],
        [0.5579, 0.2503, 0.6177]])


#### Parameter定义

In [31]:
w_tensor = torch.randn(2, 3)
# 除了 requires_grad 信息默认更改为True，其它的相当于没有变化
## requires_grad 用来标识是否需要进行参数更新(在反向传播中，会自动针对所有requires_grad为True的对象进行对应梯度的计算)
w_param = nn.Parameter(w_tensor)
print(f"Shape形状为: {w_tensor.shape} - {w_param.shape}")
print(f"数据的类型: {w_tensor.dtype} - {w_param.dtype}")
print(f"数据所在设备信息: {w_tensor.device} - {w_param.device}")
print(f"是否属于梯度更新参数: {w_tensor.requires_grad} - {w_param.requires_grad}")
print(w_tensor)
print(w_param)

Shape形状为: torch.Size([2, 3]) - torch.Size([2, 3])
数据的类型: torch.float32 - torch.float32
数据所在设备信息: cpu - cpu
是否属于梯度更新参数: False - True
tensor([[-6.8289e-01,  3.5388e-04, -1.6204e+00],
        [ 5.9875e-01, -2.8283e-01, -8.0819e-01]])
Parameter containing:
tensor([[-6.8289e-01,  3.5388e-04, -1.6204e+00],
        [ 5.9875e-01, -2.8283e-01, -8.0819e-01]], requires_grad=True)


In [32]:
w = torch.randn(2, 3)
x = torch.randn(1, 2)
print(x @ w)

tensor([[ 0.3087, -2.1368, -0.6942]])


In [33]:
pw = nn.Parameter(w)
x = x
# 当前序的执行节点上存在需要计算梯度的情况下，PyTorch默认会自动在当前算子上增加一个grad_fn用来计算相关梯度
print(x @ pw)

tensor([[ 0.3087, -2.1368, -0.6942]], grad_fn=<MmBackward0>)


In [34]:
w = nn.Parameter(torch.randn(2, 3))
x = torch.randn(1, 2)
print(x @ w) # 会有求梯度的函数自动添加
with torch.no_grad():
    # 当不需要计算梯度的时候，可以考虑使用np_grad 或者 detach
    print(x @ w) # 不会有梯度传递了
print((x @ w).detach()) # 不会有梯度传递了

tensor([[-0.7549,  1.0840,  2.5909]], grad_fn=<MmBackward0>)
tensor([[-0.7549,  1.0840,  2.5909]])
tensor([[-0.7549,  1.0840,  2.5909]])


In [35]:
## 基于参数自定义一个全连接操作
w = nn.Parameter(torch.randn(2, 3))
b = nn.Parameter(torch.tensor([0.2, 0.2, 0.2]))

x = torch.randn(1, 2)
print(x @ w) # 会有求梯度的函数自动添加
print(x @ w + b) # 会有求梯度的函数自动添加


tensor([[-0.1185,  0.0282,  0.9678]], grad_fn=<MmBackward0>)
tensor([[0.0815, 0.2282, 1.1678]], grad_fn=<AddBackward0>)


#### 最基本的模块

In [36]:
linear = nn.Linear(in_features=2, out_features=3, bias=True) # 创建模块

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
linear.to(device=device)

print(linear)

for name, param in linear.named_parameters():
    print(f"参数名称: {name} -- 参数为:\n{param}\n")

# x = torch.randn(3, 1, 2) # 当前模块的输入数据， 支持多维数据的输入
x = torch.randn(1, 2) # 当前模块的输入数据， 支持多维数据的输入
x = x.to(device=device)

r = linear(x) # 调用模块内部执行的方法
print(r)
print(x @ linear.weight.T + linear.bias) # Linear等价

Linear(in_features=2, out_features=3, bias=True)
参数名称: weight -- 参数为:
Parameter containing:
tensor([[-0.3256,  0.5173],
        [ 0.3203,  0.0582],
        [ 0.2450, -0.2832]], requires_grad=True)

参数名称: bias -- 参数为:
Parameter containing:
tensor([-0.3376,  0.0722, -0.2439], requires_grad=True)

tensor([[-0.5414,  0.1259, -0.1179]], grad_fn=<AddmmBackward0>)
tensor([[-0.5414,  0.1259, -0.1179]], grad_fn=<AddBackward0>)


In [37]:
relu = nn.ReLU() # 激活模块 y = max(0,x)
# x = torch.randn(2, 3)
x = r
print(x)
print(relu(x))

tensor([[-0.5414,  0.1259, -0.1179]], grad_fn=<AddmmBackward0>)
tensor([[0.0000, 0.1259, 0.0000]], grad_fn=<ReluBackward0>)


In [38]:
sigmoid = nn.Sigmoid() # 激活模块
# x = torch.randn(2, 3)
x = r
print(x)
print(sigmoid(x))

tensor([[-0.5414,  0.1259, -0.1179]], grad_fn=<AddmmBackward0>)
tensor([[0.3679, 0.5314, 0.4706]], grad_fn=<SigmoidBackward0>)


In [39]:
sigmoid = nn.Tanh() # 激活模块
# x = torch.randn(2, 3)
x = r
print(x)
print(sigmoid(x))

tensor([[-0.5414,  0.1259, -0.1179]], grad_fn=<AddmmBackward0>)
tensor([[-0.4941,  0.1253, -0.1174]], grad_fn=<TanhBackward0>)


In [40]:
# PyTorch封装好的序列模块，主要用来封装整个串行执行链路
## PS: 不允许使用普通python的集合列表对象，PyTorch无法识别
seq = nn.Sequential(
    nn.Linear(2, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)
for ch in seq.children():
    print(f"子模块 - {ch}")
x = torch.randn(2, 2)
r = seq(x)
print(r.shape)
print(r)

子模块 - Linear(in_features=2, out_features=3, bias=True)
子模块 - ReLU()
子模块 - Linear(in_features=3, out_features=1, bias=True)
torch.Size([2, 1])
tensor([[-0.0260],
        [-0.0024]], grad_fn=<AddmmBackward0>)


##### Softmax交叉熵损失函数

In [41]:
# 定义损失函数
loss_fn = nn.CrossEntropyLoss()

score = torch.randn(4, 5) # 4个样本，每个样本属于5个类别的置信度(线性转换后的结果，未进行softmax概率转换) -- 一般来源于网络的输出
target = torch.tensor([1, 3, 0, 0]) # 4个样本，每个样本对应的类别id 取值范围[0,5)+和类别数目有关

loss = loss_fn(score, target)
loss

tensor(1.9132)

In [42]:
# 定义损失函数
loss_fn = nn.CrossEntropyLoss()
linear = nn.Linear(3, 5)

x = torch.randn(4, 3)
score = linear(x) # 4个样本，每个样本属于5个类别的置信度 -- 一般来源于网络的输出
y = torch.tensor([1, 3, 0, 0]) # 4个样本，每个样本对应的类别id 取值范围[0,5)+和类别数目有关

loss = loss_fn(score, y)
loss

tensor(1.7690, grad_fn=<NllLossBackward0>)

In [43]:
# 定义损失函数
loss_fn = nn.CrossEntropyLoss(reduction='none')
linear = nn.Linear(3, 5)

x = torch.randn(4, 3)
score = linear(x) # 4个样本，每个样本属于5个类别的置信度 -- 一般来源于网络的输出
y = torch.tensor([1, 3, 0, 0]) # 4个样本，每个样本对应的类别id 取值范围[0,5)+和类别数目有关

loss = loss_fn(score, y)
print(f"直接损失值:\n{loss}\n")

# 按照softmax概率公式求解
proba = torch.softmax(score, dim=-1)
print(y)
print(proba)
print(-torch.log(proba))
# 获取对应位置
print(-torch.log(proba)[[0,1,2,3], y])

直接损失值:
tensor([2.8745, 2.3846, 2.0383, 1.8401], grad_fn=<NllLossBackward0>)

tensor([1, 3, 0, 0])
tensor([[0.1087, 0.0564, 0.2855, 0.3818, 0.1675],
        [0.1493, 0.1421, 0.1096, 0.0921, 0.5069],
        [0.1302, 0.0877, 0.2104, 0.2348, 0.3369],
        [0.1588, 0.1167, 0.1941, 0.2017, 0.3286]], grad_fn=<SoftmaxBackward0>)
tensor([[2.2193, 2.8745, 1.2534, 0.9627, 1.7868],
        [1.9020, 1.9512, 2.2108, 2.3846, 0.6795],
        [2.0383, 2.4343, 1.5589, 1.4490, 1.0880],
        [1.8401, 2.1478, 1.6394, 1.6008, 1.1128]], grad_fn=<NegBackward0>)
tensor([2.8745, 2.3846, 2.0383, 1.8401], grad_fn=<NegBackward0>)


##### Sigmoid交叉熵损失函数

In [42]:
# 定义损失函数
loss_fn = nn.BCEWithLogitsLoss()

score = torch.randn(4, 5) # 4个样本，每个样本属于5个类别的置信度 -- 一般来源于网络的输出
target = torch.tensor([
    [1, 1, 0, 0, 0], # 第一个样本属于类别1和类别2，并且属于1和类别2的可信度为1
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0], # 第三个样本不属于任何类别
    [1, 0, 0, 1, 0]
], dtype=torch.float32) # 4个样本，属于当前类别，标签为1，不属于标签为0

loss = loss_fn(score, target)
loss

tensor(0.6953)

In [43]:
# 定义损失函数
loss_fn = nn.BCEWithLogitsLoss(reduction='none')

score = torch.randn(4, 5) # 4个样本，每个样本属于5个类别的置信度 -- 一般来源于网络的输出
target = torch.tensor([
    [1, 1, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0]
], dtype=torch.float32) # 4个样本，属于当前类别，标签为1，不属于标签为0

loss = loss_fn(score, target)
loss

tensor([[0.6526, 0.5615, 0.8809, 0.7423, 0.7278],
        [0.3327, 0.5462, 1.9410, 0.5155, 1.3614],
        [0.9619, 1.0398, 0.9559, 0.6892, 0.4244],
        [0.5036, 0.1808, 0.8269, 0.7425, 0.2410]])

In [46]:
# 按照sigmoid概率公式求解
proba = torch.sigmoid(score)
print("=" * 20, "\n", "实际值:")
print(target)
print("=" * 20, "\n", "预测概率:")
print(proba)
print("=" * 20, "\n", "-log(概率):")
print(-torch.log(proba))
print("=" * 20, "\n", "-log(1-概率):")
print(-torch.log(1 - proba))
print("=" * 20, "\n", "损失值:")
print(loss)


 实际值:
tensor([[1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0.]])
 预测概率:
tensor([[0.5207, 0.5704, 0.5856, 0.5240, 0.5170],
        [0.2830, 0.4209, 0.8564, 0.5972, 0.7437],
        [0.6178, 0.6465, 0.6155, 0.4980, 0.3458],
        [0.6044, 0.1654, 0.5626, 0.4759, 0.2142]])
 -log(概率):
tensor([[0.6526, 0.5615, 0.5352, 0.6463, 0.6597],
        [1.2622, 0.8654, 0.1550, 0.5155, 0.2961],
        [0.4815, 0.4362, 0.4852, 0.6971, 1.0618],
        [0.5036, 1.7993, 0.5752, 0.7425, 1.5410]])
 -log(1-概率):
tensor([[0.7354, 0.8448, 0.8809, 0.7423, 0.7278],
        [0.3327, 0.5462, 1.9410, 0.9093, 1.3614],
        [0.9619, 1.0398, 0.9559, 0.6892, 0.4244],
        [0.9273, 0.1808, 0.8269, 0.6461, 0.2410]])
 损失值:
tensor([[0.6526, 0.5615, 0.8809, 0.7423, 0.7278],
        [0.3327, 0.5462, 1.9410, 0.5155, 1.3614],
        [0.9619, 1.0398, 0.9559, 0.6892, 0.4244],
        [0.5036, 0.1808, 0.8269, 0.7425, 0.2410]])
